apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-online-api-eks
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: shop-online-api-eks
          image: 679803656105.dkr.ecr.eu-central-1.amazonaws.com/shop-online-api-ecr:0.0.1
          ports:
            - containerPort: 8000
