version: "3.9"

services:
  fastapi_service:
    image: mykytareva/shop-online-api:0.0.1
    hostname: fastapi_service
    container_name: fastapi_service
    ports:
      - "8000:8000"
    env_file:
      - .env
#    volumes:
#      - ./:/home/app
    networks:
      - my-net

#  db_postgres:
#    image: postgres:14.3-alpine
#    hostname: db_postgres
#    container_name: db_postgres
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-postgres:/var/lib/postgresql/data
#    networks:
#      - my-net
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi_service
    networks:
      - my-net

#volumes:
#  db-postgres:
#    driver: local

networks:
  my-net:
    external: true
