name: shop-online-api
channels:
  - conda-forge
dependencies:
    - python=3.10
    - boto3=1.24.28
    - fastapi=0.101.0
    - Faker=19.2.0
    - passlib=1.7.4
    - python-multipart=0.0.6
    - SQLAlchemy=2.0.19
    - uvicorn=0.23.2
    - email-validator=2.0.0.post2
    - python-jose=3.3.0
    - pytest=7.4.0
    - pip=23
    - pre-commit=3.3
    - git
